import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gelion = localFont({
  src: [
    {
      path: "../../public/fonts/Gelion-Medium.ttf",
      weight: "500",
    },
    {
      path: "../../public/fonts/Gelion-Regular.ttf",
      weight: "400",
    },
  ],
  variable: "--font-gelion",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gelion.variable} font-sans`}>{children}</body>
    </html>
  );
}
